library(tidyverse)
data_set <- read_csv("data_set.csv")
data_set <- na.omit(data_set)
data_set
library(skimr)
data_set %>% skimr::skim()

data_set <- select(data_set, -ARS_GOV_1Y)
data_set <- select(data_set, -CLP_GOV_10Y)
data_set <- select(data_set, -CNH_SWAP_SPREAD_2Y)
data_set <- select(data_set, -THB_INFL_2Y)
data_set <- select(data_set, -BGN_GOV_1Y)
data_set <- select(data_set, -NGN_GOV_1Y)
data_set <- select(data_set, -COP_INFL_5Y)
data_set <- select(data_set, -COP_INFL_30Y)  
data_set <- select(data_set, -CNH_SWAP_SPREAD_10Y)
data_set <- select(data_set, -HRK_GOV_30Y)
data_set <- select(data_set, -NGN_GOV_5Y)
data_set <- select(data_set, -SE_CDT_DTS_CORP)
data_set <- select(data_set, -ISK_GOV_30Y)
data_set <- select(data_set, -CLP_INFL_10Y)
data_set <- select(data_set, -CNH_SWAP_SPREAD_30Y)
data_set <- select(data_set, -DOP_GOV_1Y)
data_set <- select(data_set, -KRW_INFL_5Y)
data_set <- select(data_set, -PLN_INFL_10Y)
data_set <- select(data_set, -ARS_GOV_5Y)
data_set <- select(data_set, -LKR_GOV_10Y)
data_set <- select(data_set, -NGN_GOV_2Y)
data_set <- select(data_set, -ISK_GOV_2Y)
data_set <- select(data_set, -NO_CDT_DTS_UTL)
data_set <- select(data_set, -LKR_GOV_30Y)
data_set <- select(data_set, -CLP_INFL_2Y)
data_set <- select(data_set, -CLP_INFL_1Y)
data_set <- select(data_set, -THB_INFL_5Y)
data_set <- select(data_set, -KRW_INFL_2Y)
data_set <- select(data_set, -DOP_GOV_2Y)
data_set <- select(data_set, -CLP_GOV_2Y)
data_set <- select(data_set, -THB_INFL_30Y)
data_set <- select(data_set, -COP_INFL_1Y)
data_set <- select(data_set, -CNH_GOV_1Y)
data_set <- select(data_set, -BGN_GOV_30Y)
data_set <- select(data_set, -ISK_GOV_20Y)
data_set <- select(data_set, -ISK_GOV_10Y)
data_set <- select(data_set, -EGP_GOV_30Y)
data_set <- select(data_set, -JP_CDT_DTS_SHINS)
data_set <- select(data_set, -CNH_SWAP_SPREAD_1Y)
data_set <- select(data_set, -CUR2L_CNHC)
data_set <- select(data_set, -THB_INFL_10Y)
data_set <- select(data_set, -ISK_GOV_6M)
data_set <- select(data_set, -DOP_GOV_5Y)
data_set <- select(data_set, -DOP_GOV_10Y)
data_set <- select(data_set, -ISK_GOV_1M)
data_set <- select(data_set, -CUR2L_TOFC)
data_set <- select(data_set, -ARS_GOV_30Y)
data_set <- select(data_set, -CNH_SWAP_SPREAD_5Y)
data_set <- select(data_set, -HRK_GOV_5Y)
data_set <- select(data_set, -ARS_GOV_10Y)
data_set <- select(data_set, -THB_INFL_1Y)
data_set <- select(data_set, -PLN_INFL_5Y)
data_set <- select(data_set, -PLN_INFL_2Y)
data_set <- select(data_set, -TRY_INFL_1Y)
data_set <- select(data_set, -SE_CDT_DTS_FIN)
data_set <- select(data_set, -ISK_GOV_1Y)
data_set <- select(data_set, -ARS_GOV_2Y)
data_set <- select(data_set, -BGN_GOV_2Y)
data_set <- select(data_set, -ISK_GOV_50Y)
data_set <- select(data_set, -ISK_GOV_5Y)
data_set <- select(data_set, -CLP_INFL_5Y)
data_set <- select(data_set, -CLP_GOV_5Y)
data_set <- select(data_set, -COP_INFL_2Y)
data_set <- select(data_set, -HRK_GOV_1Y)
data_set <- select(data_set, -HRK_GOV_10Y)
data_set <- select(data_set, -HRK_GOV_2Y)
data_set <- select(data_set, -TRY_INFL_30Y)
data_set <- select(data_set, -LKR_GOV_1Y)
data_set <- select(data_set, -EGP_GOV_5Y)
data_set <- select(data_set, -TRY_INFL_5Y)
data_set <- select(data_set, -TRY_INFL_2Y)
data_set <- select(data_set, -EGP_GOV_1Y)
data_set <- select(data_set, -CLP_GOV_1Y)
data_set <- select(data_set, -BGN_GOV_5Y)
data_set <- select(data_set, -COP_INFL_10Y)
data_set <- select(data_set, -TRY_INFL_10Y)
data_set <- select(data_set, -PLN_INFL_1Y)
data_set <- select(data_set, -EGP_GOV_2Y)
data_set <- select(data_set, -CNH_GOV_10Y)
data_set <- select(data_set, -CLP_INFL_30Y)
data_set <- select(data_set, -NO_CDT_DTS_FIN)
data_set <- select(data_set, -EGP_GOV_10Y)
data_set <- select(data_set, -UYU_GOV_1Y)
data_set <- select(data_set, -UYU_GOV_30Y)
data_set <- select(data_set, -UYU_GOV_2Y)
data_set <- select(data_set, -UYU_GOV_5Y)
data_set <- select(data_set, -UYU_GOV_10Y)
data_set <- select(data_set, -EUR_FRA_INFL_50Y)
sink("output2.txt")
data_set %>% skimr::skim()
data_set_omit <- na.omit(data_set)
data_set_omit <- select(data_set_omit, -Date)

lm2 <- lm(return~.,data=data_set_omit)
summary(lm2)
sink("outputlm.txt")
summary(lm2)
sink()

sink("outputlm.txt")
summary(lm2)
sink()

fwd.model <- step(
  min.model,
  direction = "forward",
  scope = (~.),
  data=data_set_omit,
  trace = 0
)


lm3 <- lm(return　~ USD_MBS_ALL + USD_MBS_CONVENTIONAL_15YR + US_CDT_DTS_COND_MEDIA_IG + US_CDT_DTS_COND_HY + USD_BASIS_OTR_1Y + USD_BASIS_OTR_10Y + USD_GOV_1Y + USD_MUNI_1Y + US_CDT_DTS_CONS_RET_IG + USD_MBS_CONVENTIONAL_30YR + US_CDT_DTS_FIN_CAPMK_IG + US_CDT_DTS_MAT_HY + USD_SWAP_SPREAD_5Y + US_CDT_DTS_TEL_DVRST_IG + USD_GOV_5Y + USD_MUNI_DTS_SPREAD + USD_MUNI_30Y + US_CDT_DTS_HLTH_PHRM_IG + US_CDT_DTS_FIN_HY + USD_INFL_20Y + USD_GOV_20Y + US_CDT_DTS_ENGY_HY + US_CDT_DTS_FIN_BANK_HY + USD_GOV_30Y + USD_GOV_2Y + US_CDT_DTS_FIN_REAL_IG + US_CDT_DTS_HLTH_HY + US_CDT_DTS_TEL_IG + USD_LOAN_TRANS + USD_LOAN_FIN + USD_MBS_GNMA_15YR + USD_GOV_6M + USD_BASIS_OTR_5Y + USD_INFL_30Y + USD_LOAN_TEL + US_CDT_DTS_COND_SERV_IG + US_CDT_DTS_UTL_ELTC_IG + US_CDT_DTS_UTL_IG + US_CDT_DTS_MAT_IG + US_CDT_DTS_COND_RET_IG + US_CDT_DTS_HLTH_IG + USD_LOAN_UTL + US_CDT_DTS_MAT_CHEM_IG + USD_INFL_50Y + USD_INFL_2Y + USD_LOAN_IND + US_CDT_DTS_UTL_HY + US_CDT_DTS_AGNCY + USD_INFL_1Y + US_CDT_DTS_COND_DURAP_IG + USD_ABS_UTILITIES + USD_ABS_STUDENT_LOAN + USD_SWAP_SPREAD_2Y + US_CDT_DTS_TECH_IG + USD_SWAP_SPREAD_30Y + USD_SWAP_SPREAD_1M + US_CDT_DTS_TECH_HARD_IG + USD_ABS_AUTO + USD_SWAP_SPREAD_1Y + US_CDT_DTS_HLTH_EQSV_IG + USD_MBS_CONVENTIONAL + USD_MBS_CURRENT_COUPON + USD_INFL_5Y + USD_MUNI_10Y + USD_INFL_10Y + US_CDT_DTS_IND_IG + USD_ABS_MANUFACTURED + US_CDT_DTS_UTL_MULTI_IG + USD_IMPVOL_IMPLIED_VOL + US_CDT_DTS_CONS_FOOD_IG + US_CDT_DTS_CONS_HY + US_CDT_DTS_COND_AUTOM_IG + USD_SWAP_SPREAD_10Y + USD_MBS_GNMA_30YR + US_CDT_DTS_TEL_HY + USD_ABS_HOME_EQUITY + US_CDT_DTS_TECH_SOFT_IG + USD_LOAN_ENGY + USD_ABS_ALL + USD_ABS_CREDIT_CARD + US_CDT_DTS_TECH_SEMI_IG + USD_GOV_50Y + USD_MUNI_5Y + USD_BASIS_CDS_IG + US_CDT_DTS_SOVSUP + US_CDT_DTS_FIN_IG + US_CDT_DTS_ENGY_IG + USD_GOV_1M + US_CDT_DTS_TRANS_GND_IG + US_CDT_DTS_IND_SERV_IG + US_CDT_DTS_TECH_HY + USD_MUNI_2Y + US_CDT_DTS_CORP_IG + US_CDT_DTS_TRANS_HY + USD_LOAN_MAT + US_CDT_DTS_IND_CAPGD_IG + US_CDT_DTS_COND_IG + USD_MUNI_6M + USD_ABS_MISCELLANEOUS + US_CDT_DTS_ENGY_EQSV_IG + USD_CMBS_ALL + USD_LOAN_CONS + US_CDT_DTS_ENGY_OILGS_IG + USD_BASIS_CDS_HY + USD_LOAN_ALL + USD_LOAN_COND + US_CDT_DTS_FIN_DVRSF_IG + US_CDT_DTS_CORP_HY + USD_SWAP_SPREAD_6M + USD_GOV_10Y + USD_SWAP_SPREAD_50Y + USD_MBS_GNMA + US_CDT_DTS_TEL_WIREL_IG + USD_MUNI_20Y + US_CDT_DTS_TRANS_IG + US_CDT_DTS_CONS_PROD_IG + US_CDT_DTS_FIN_INSR_IG + US_CDT_DTS_CONS_IG + US_CDT_DTS_FIN_BANK_IG + US_CDT_DTS_MAT_MET_IG + USD_LOAN_HLTH + USD_SWAP_SPREAD_20Y + US_CDT_DTS_IND_HY,
          data=data_set_omit)
